version: "3.8" # local development environment
services:
  backend:
    container_name: workout-tracker-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/app
    tty: true
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: workout-tracker-app-postgres
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./backend/app.env

volumes:
  postgresDB:
