version: "3.8"
services:
  backend:
    container_name: workout-tracker-app-backend
    environment:
      GIN_MODE: "release"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./backend/app.env

  db:
    image: postgres:13
    container_name: workout-tracker-app-postgres
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./backend/app.env

volumes:
  postgresDB:
