version: "3.8"
services:
  backend:
    container_name: workout-tracker-app-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/production.env
